# AnKhangCRM MySQL Configuration
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: <%= ENV.fetch("DB_USER", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  host: <%= ENV.fetch("DB_HOST", "db") %>

development:
  <<: *default
  database: ankhang_crm_development
  ssl_mode: disabled

test:
  <<: *default
  database: ankhang_crm_test

production:
  primary:
    <<: *default
    database: ankhang_crm_production
    username: <%= ENV["APP_DATABASE_USER"] %>
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *default
    database: ankhang_crm_production
    username: <%= ENV["APP_DATABASE_USER"] %>
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: ankhang_crm_production
    username: <%= ENV["APP_DATABASE_USER"] %>
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
    migrations_paths: db/queue_migrate
